### ISSUE TITLE
Do the unit tests cover test vectors from spec?

### ISSUE THREAD

**Issue by tuupola** [AmanAgnihotri/Branca#1]
Since the unit test format is not familiar to me I ask here. Do the unit tests cover all the [test vectors](https://github.com/tuupola/branca-spec/blob/master/test_vectors.json) from the spec? It looks like it, but I am not 100% sure.

**Comment by AmanAgnihotri** [comment]
Hello! It's only now that I am noticing this question so apologies for the delay.

I sure have tackled each and every test vector mentioned in your specification. 

In your test vectors, encoding and decoding come with 8 valid tests:

1. Hello world with zero timestamp
2. Hello world with max timestamp
3. Hello world with November 27 timestamp
4. Eight null bytes with zero timestamp
5. Eight null bytes with max timestamp
6. Eight null bytes with November 27th timestamp
7. Empty payload
8. Non-UTF8 payload

They can be found here:

[Encoding/Decoding Related Valid Test Data](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/BrancaTests.cs#L46)

The valid test data is fed to the [EncodeAndDecodeValidCasesProperly](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/BrancaTests.cs#L13) test function which both encodes and decodes and validates the data accordingly.

Then in the decoding section, starting from id 16, you have 8 invalid test vectors:

1. Wrong version 0xBB
2. Invalid base62 characters
3. Modified version
4. Modified first byte of the nonce
5. Modified timestamp
6. Modified last byte of the ciphertext
7. Modified last byte of the Poly1305 tag
8. Wrong key

They can be found here:

[Decoding Related Invalid Test Data](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/BrancaTests.cs#L66)

The invalid test data is fed to the [FailToDecodeInvalidCases](https://github.com/AmanAgnihotri/Branca/blob/841fa4c34c18eb863ec25fd183171ac121b30789/test/Branca.Tests/BrancaTests.cs#L34) test function which decodes the invalid data and fails accordingly.

Note that `data.IsValid` is `true` in the case of the valid test data and `data.IsValid` is `false` in the case of invalid test data, so the strict equal assertion on the decoding looks the same in both test functions.

Then finally in your test vectors is the id 24 test, regarding invalid key. I take care of it in here along with three more tests concerning keys not mentioned in the test vectors: [HexKeyTests](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/HexKeyTests.cs).

For the sake of some separation, I put all the test data in separate classes:

1. All Keys can be found in [TestData.Keys](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/TestData.Keys.cs).
2. All Messages can be found in [TestData.Messages](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/TestData.Messages.cs).
3. All Nonces can be found in [TestData.Nonces](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/TestData.Nonces.cs).
4. All Timestamps can be found in [TestData.Timestamps](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/TestData.Timestamps.cs).
5. All Tokens can be found in [TestData.Tokens](https://github.com/AmanAgnihotri/Branca/blob/main/test/Branca.Tests/TestData.Tokens.cs).

I could have used JSON to load the data but then this const-based hardcoding was not much effort so I went along with it.

If you are on macOS environment, you can use [Homebrew](https://brew.sh) to install `dotnet` by doing:

`brew install dotnet-sdk`

Can then change directory to the Branca folder that you have locally downloaded, to the location where the `.sln` [Solution] file is. At that point you can run the following command:

`dotnet test` and all the 20 tests that I have written will get triggered. They are 20 tests because the 8 valid test data get tested for both encoding and decoding in the same function which counts as 8 in total instead of 16 as is the case in your test vectors. Then we have 8 invalid test data, so a total of 16 so far. Then 4 additional tests on keys, 2 valid and 2 invalid. One of the two invalid key tests is the last test vector in your list.

Hopefully this clarifies it. Thank you again for making the Branca specification.

**Comment by tuupola** [comment]
No problem :) I asked because I will do separate lists for implementations with full unit tests and implementations without full tests. This clarifies it. Thanks!
